# Generated by Django 4.2.7 on 2025-08-11 22:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("funcionario", "Funcionário"),
                            ("supervisor", "Supervisor"),
                        ],
                        default="funcionario",
                        max_length=20,
                    ),
                ),
                (
                    "valor_hora",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor por hora em R$",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("data_admissao", models.DateField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis",
            },
        ),
    ]
