# Generated by Django 4.2.7 on 2025-08-11 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descricao", models.CharField(max_length=200)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Código de Trabalho",
                "verbose_name_plural": "Códigos de Trabalho",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="TimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("entrada1", models.TimeField(blank=True, null=True)),
                ("saida1", models.TimeField(blank=True, null=True)),
                ("entrada2", models.TimeField(blank=True, null=True)),
                ("saida2", models.TimeField(blank=True, null=True)),
                ("entrada3", models.TimeField(blank=True, null=True)),
                ("saida3", models.TimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("aprovado", models.BooleanField(default=False)),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_aprovados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="timetrack.workcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ponto",
                "verbose_name_plural": "Registros de Ponto",
                "ordering": ["-data"],
                "unique_together": {("user", "data")},
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.PositiveIntegerField()),
                ("ano", models.PositiveIntegerField()),
                (
                    "horas_trabalhadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("calculando", "Calculando"),
                            ("pendente", "Pendente Aprovação"),
                            ("aprovado", "Aprovado"),
                            ("pago", "Pago"),
                        ],
                        default="calculando",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salário",
                "verbose_name_plural": "Salários",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("user", "mes", "ano")},
            },
        ),
    ]
