# Generated by Django 4.2.7 on 2025-08-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetrack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timerecord",
            name="aprovado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="work_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="timetrack.workcode",
            ),
        ),
    ]
