# Generated by Django 4.2.7 on 2025-08-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetrack", "0002_alter_timerecord_aprovado_alter_timerecord_work_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timerecord",
            unique_together=set(),
        ),
    ]
