# Generated by Django 4.2.7 on 2025-08-12 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetrack", "0003_alter_timerecord_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timerecord",
            unique_together={("user", "data")},
        ),
    ]
