# Generated by Django 4.2.7 on 2025-08-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetrack", "0004_alter_timerecord_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timerecord",
            name="aprovado",
        ),
        migrations.RemoveField(
            model_name="timerecord",
            name="aprovado_em",
        ),
        migrations.RemoveField(
            model_name="timerecord",
            name="aprovado_por",
        ),
    ]
