# Generated by Django 4.2.7 on 2025-08-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetrack", "0005_remove_timerecord_aprovado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timerecord",
            name="aprovado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timerecord",
            name="aprovado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timerecord",
            name="aprovado_por",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
