# Generated by Django 4.2.7 on 2025-08-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetrack", "0006_timerecord_aprovado_timerecord_aprovado_em_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timerecord",
            name="aprovado",
        ),
        migrations.RemoveField(
            model_name="timerecord",
            name="aprovado_em",
        ),
        migrations.RemoveField(
            model_name="timerecord",
            name="aprovado_por",
        ),
    ]
